Install Nginx as described here:

`https://www.digitalocean.com/community/tutorials/how-to-install-nginx-on-ubuntu-16-04`

Assign hostname to the VM and then 

Create self-signed certs to start NGINX using the following command:

sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt

Now, create a NGINX conf file as follows:
```
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
sudo vi /etc/nginx/sites-available/default
```
Add the following content to it:

```

server {

    listen      80;
    server_name https-server.westus.cloudapp.azure.com;
    access_log on;
    error_log off;
    ## redirect http to https ##
    return      301 https://$server_name$request_uri;
}

server {

    listen 443 default;
    server_name https://https-server.westus.cloudapp.azure.com;
    ssl_certificate /etc/letsencrypt/live/https-server.westus.cloudapp.azure.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/https-server.westus.cloudapp.azure.com/privkey.pem; # managed by Certbot

    ssl on;
    ssl_session_cache  builtin:1000  shared:SSL:10m;
    ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
    ssl_prefer_server_ciphers on;

    access_log            /var/log/nginx/jenkins.access.log;

    location / {

      proxy_set_header        Host $host;
      proxy_set_header        X-Real-IP $remote_addr;
      proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header        X-Forwarded-Proto $scheme;
      proxy_set_header        Authorization "Basic aWxsdW1pby1zaGFyZWQtc2VjcmV0LWtleQ==";
      proxy_set_header        X-Query-Vendor "test";
 
      # Fix the “It appears that your reverse proxy set up is broken" error.
      proxy_pass          http://10.0.0.5:5000;
      proxy_read_timeout  90;

      proxy_redirect      http://10.0.0.5:5000 https://https-server.westus.cloudapp.azure.com;
    }
  

}
```
Instead of the letsencrypt cert-path, add the paths of the certs generated by the openssl and then

`sudo service nginx restart`

Once, nginx is up & running, configure the firewall to open port 80 because letsencrypt certbot will do the check

Now, install certbot as described here:


`https://certbot.eff.org/lets-encrypt/ubuntuxenial-nginx`


Once, certbot is installed, run the following command:

`sudo certbot --nginx -d https-server.westus.cloudapp.azure.com`

Once, that succeeds, you can login to https://https-server.westus.cloudapp.azure.com on the browser
